<a href="https://colab.research.google.com/github/knshkp/deep-learning-keras-tf-tutorial/blob/master/cnnoncifar10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import datasets,layers,models

In [21]:
y_train[:5]

array([[0.02352941],
       [0.03529412],
       [0.03529412],
       [0.01568627],
       [0.00392157]])

In [22]:
y_train=y_train.reshape(-1,)
y_train[:5]

array([0.02352941, 0.03529412, 0.03529412, 0.01568627, 0.00392157])

In [23]:
(X_train,y_train),(X_test,y_test)=datasets.cifar10.load_data()

In [24]:
classes=['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']

In [25]:
def plot_sample(X,y,index):
  plt.figure(figsize=(15,2))
  plt.imshow(x[index])
  plt.xlabel(y[index])

In [26]:
X_train=X_train/255
X_test=X_test/255

In [27]:
ann=models.Sequential([
                       layers.Flatten(input_shape=(32,32,3)),
                       layers.Dense(3000,activation='relu'),
                       layers.Dense(1000,activation='relu'),
                       layers.Dense(10,activation='sigmoid'),
                      
])
ann.compile(optimizer='SGD',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])
ann.fit(X_train,y_train,epochs=5)

Epoch 1/5
1563/1563 [==============================] - 112s 71ms/step - loss: 1.8127 - accuracy: 0.3535
Epoch 2/5
1563/1563 [==============================] - 108s 69ms/step - loss: 1.6219 - accuracy: 0.4272
Epoch 3/5
1563/1563 [==============================] - 106s 68ms/step - loss: 1.5423 - accuracy: 0.4555
Epoch 4/5
1563/1563 [==============================] - 110s 70ms/step - loss: 1.4810 - accuracy: 0.4793
Epoch 5/5
1563/1563 [==============================] - 109s 70ms/step - loss: 1.4320 - accuracy: 0.4962


In [28]:
y_train[:5]

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [33]:
cnn=models.Sequential([
                      layers.Conv2D(filters=64,kernel_size=(3,3),activation='relu',input_shape=(32,32,3)),
                      layers.MaxPooling2D((2,2)),
                      layers.Conv2D(filters=64,kernel_size=(3,3),activation='relu'),
                      layers.MaxPooling2D((2,2)),
                      layers.Flatten(),
                      layers.Dense(64,activation='relu'),
                      layers.Dense(10,activation='softmax'),


])

In [34]:
cnn.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'],
            
            )

In [35]:
cnn.fit(X_train,y_train,epochs=10)

Epoch 1/10
1563/1563 [==============================] - 111s 71ms/step - loss: 1.4629 - accuracy: 0.4738
Epoch 2/10
1563/1563 [==============================] - 111s 71ms/step - loss: 1.1111 - accuracy: 0.6101
Epoch 3/10
1563/1563 [==============================] - 111s 71ms/step - loss: 0.9774 - accuracy: 0.6594
Epoch 4/10
1563/1563 [==============================] - 111s 71ms/step - loss: 0.8907 - accuracy: 0.6904
Epoch 5/10
1563/1563 [==============================] - 111s 71ms/step - loss: 0.8263 - accuracy: 0.7146
Epoch 6/10
1563/1563 [==============================] - 110s 70ms/step - loss: 0.7747 - accuracy: 0.7318
Epoch 7/10
1563/1563 [==============================] - 111s 71ms/step - loss: 0.7251 - accuracy: 0.7467
Epoch 8/10
1563/1563 [==============================] - 111s 71ms/step - loss: 0.6853 - accuracy: 0.7596
Epoch 9/10
1563/1563 [==============================] - 110s 71ms/step - loss: 0.6487 - accuracy: 0.7751
Epoch 10/10
1563/1563 [==============================] 